#!/bin/bash
docker build -t ashrielbrian/wandb_action -f prebuild.Dockerfile .

INPUT_WANDB_API_KEY=
INPUT_PROJECT_NAME=
GITHUB_WORKSPACE="/data"
GITHUB_SHA=
INPUT_DISPLAY_METRICS="['metrics/precision', 'metrics/mAP_0.5:0.95', 'metrics/mAP_0.5', 'metrics/recall']"
INPUT_DISPLAY_CONFIG_VARS="[]"
INPUT_BASELINE_TAGS="['baseline', 'reference']"
INPUT_DEBUG="y"


docker run \
-e INPUT_FILTER_GITHUB_SHA=$GITHUB_SHA \
-e INPUT_FILTER_SECONDARY_SHA="" \
-e INPUT_PROJECT_NAME=$INPUT_PROJECT_NAME \
-e INPUT_BASELINE_TAGS="$INPUT_BASELINE_TAGS" \
-e INPUT_DISPLAY_METRICS="$INPUT_DISPLAY_METRICS" \
-e INPUT_DISPLAY_CONFIG_VARS="$INPUT_DISPLAY_CONFIG_VARS" \
-e INPUT_WANDB_API_KEY=$INPUT_WANDB_API_KEY \
-e GITHUB_WORKSPACE=$GITHUB_WORKSPACE \
-e INPUT_DEBUG=$INPUT_DEBUG \
-v ${PWD}:/data/ \
ashrielbrian/wandb_action